// More chains and typical restaurant kinds. All values are rounded estimates (US sizes for US chains), not official figures.
// Row: [id, nameDe, nameEn, category, kcal, protein, carbs, fat, max, weight]
const COLA = ["cola", "Coca-Cola (0,4 l)", "Coca-Cola (0.4 l)", "drink", 170, 0, 42, 0];
const COLA_ZERO = ["colazero", "Coca-Cola Zero (0,4 l)", "Coca-Cola Zero (0.4 l)", "drink", 2, 0, 0, 0];
const DRINKS = [COLA, COLA_ZERO];

export const MORE_CHAINS = [
  /* ---------------- chains ---------------- */
  {
    id: "wendys", name: "Wendy's", emoji: "🍔", color: "#E2203D", type: "burger",
    items: [
      ["dave1", "Dave's Single", "Dave's Single", "main", 590, 30, 39, 34],
      ["dave2", "Dave's Double", "Dave's Double", "main", 810, 49, 40, 48, 1],
      ["bacon", "Baconator", "Baconator", "main", 950, 57, 38, 62, 1],
      ["jrcheese", "Jr. Cheeseburger", "Jr. Cheeseburger", "main", 290, 15, 26, 13, 3, 0.7],
      ["spicy", "Spicy Chicken Sandwich", "Spicy Chicken Sandwich", "main", 500, 29, 51, 21],
      ["grilled", "Gegrilltes Chicken Sandwich", "Grilled Chicken Sandwich", "main", 370, 34, 38, 10],
      ["nug10", "Chicken Nuggets (10 Stk.)", "Chicken Nuggets (10 pcs)", "starter", 450, 23, 26, 29, 1],
      ["nug4", "Chicken Nuggets (4 Stk.)", "Chicken Nuggets (4 pcs)", "starter", 170, 9, 10, 11],
      ["chili", "Chili (klein)", "Chili (small)", "side", 240, 17, 23, 7],
      ["potato", "Ofenkartoffel (natur)", "Baked potato (plain)", "side", 270, 7, 61, 0],
      ["friesm", "Pommes mittel", "Fries medium", "side", 350, 5, 50, 15],
      ["frosty", "Frosty (klein)", "Frosty (small)", "dessert", 340, 9, 53, 9],
      ...DRINKS,
    ],
  },
  {
    id: "tacobell", name: "Taco Bell", emoji: "🌮", color: "#702082", type: "mexican",
    items: [
      ["crunchy", "Crunchy Taco", "Crunchy Taco", "main", 170, 8, 13, 10, 4, 0.4],
      ["soft", "Soft Taco", "Soft Taco", "main", 180, 9, 18, 9, 4, 0.4],
      ["crunchwrap", "Crunchwrap Supreme", "Crunchwrap Supreme", "main", 530, 16, 71, 21],
      ["burrito", "Burrito Supreme (Rind)", "Burrito Supreme (beef)", "main", 390, 16, 51, 14],
      ["quesa", "Chicken Quesadilla", "Chicken Quesadilla", "main", 520, 27, 37, 28],
      ["chalupa", "Chalupa Supreme", "Chalupa Supreme", "main", 350, 14, 30, 20],
      ["gordita", "Cheesy Gordita Crunch", "Cheesy Gordita Crunch", "main", 500, 20, 41, 28],
      ["bowl", "Power Bowl Chicken", "Power Bowl Chicken", "main", 470, 26, 50, 18],
      ["pizza", "Mexican Pizza", "Mexican Pizza", "main", 540, 20, 46, 30],
      ["nachos", "Nachos BellGrande", "Nachos BellGrande", "main", 740, 16, 80, 38, 1],
      ["beans", "Schwarze Bohnen & Reis", "Black beans & rice", "side", 170, 4, 30, 3],
      ["twists", "Cinnamon Twists", "Cinnamon Twists", "dessert", 170, 1, 26, 7],
      ...DRINKS,
    ],
  },
  {
    id: "chipotle", name: "Chipotle", emoji: "🌯", color: "#A81612", type: "mexican",
    items: [
      ["chicken", "Poulet (115 g)", "Chicken (4 oz)", "main", 180, 32, 0, 7, 2, 0.5],
      ["steak", "Steak (115 g)", "Steak (4 oz)", "main", 150, 21, 1, 6, 2, 0.5],
      ["carnitas", "Carnitas (115 g)", "Carnitas (4 oz)", "main", 210, 23, 0, 12, 2, 0.5],
      ["barbacoa", "Barbacoa (115 g)", "Barbacoa (4 oz)", "main", 170, 24, 2, 7, 2, 0.5],
      ["sofritas", "Sofritas (115 g)", "Sofritas (4 oz)", "main", 150, 8, 9, 10, 2, 0.5],
      ["rice", "Weisser Reis", "White rice", "side", 210, 4, 40, 4],
      ["beans", "Schwarze Bohnen", "Black beans", "extra", 130, 8, 22, 1.5],
      ["lettuce", "Salat & Salsa", "Lettuce & salsa", "salad", 40, 2, 8, 0],
      ...DRINKS,
    ],
  },
  {
    id: "cfa", name: "Chick-fil-A", emoji: "🐔", color: "#E51636", type: "chicken",
    items: [
      ["sand", "Chicken Sandwich", "Chicken Sandwich", "main", 440, 28, 41, 17],
      ["spicy", "Spicy Chicken Sandwich", "Spicy Chicken Sandwich", "main", 450, 29, 41, 19],
      ["grilled", "Gegrilltes Chicken Sandwich", "Grilled Chicken Sandwich", "main", 390, 28, 44, 12],
      ["wrap", "Grilled Cool Wrap", "Grilled Cool Wrap", "main", 350, 37, 29, 12],
      ["nug8", "Nuggets (8 Stk.)", "Nuggets (8 pcs)", "starter", 250, 28, 11, 11],
      ["nug12", "Nuggets (12 Stk.)", "Nuggets (12 pcs)", "starter", 380, 40, 16, 17],
      ["gnug8", "Gegrillte Nuggets (8 Stk.)", "Grilled nuggets (8 pcs)", "starter", 130, 25, 2, 3],
      ["cobb", "Cobb Salat", "Cobb salad", "salad", 510, 40, 28, 27],
      ["waffle", "Waffle Fries (mittel)", "Waffle fries (medium)", "side", 420, 5, 45, 24],
      ["fruit", "Fruchtbecher", "Fruit cup", "side", 50, 1, 13, 0],
      ["icedream", "Icedream (Becher)", "Icedream cup", "dessert", 170, 4, 28, 4],
      ...DRINKS,
    ],
  },
  {
    id: "popeyes", name: "Popeyes", emoji: "🍗", color: "#F26B26", type: "chicken",
    items: [
      ["classic", "Classic Chicken Sandwich", "Classic Chicken Sandwich", "main", 700, 28, 50, 42],
      ["breast", "Hähnchenbrust (mit Knochen)", "Chicken breast (bone-in)", "main", 380, 31, 12, 22, 3, 0.8],
      ["thigh", "Hähnchenschenkel (mit Knochen)", "Chicken thigh (bone-in)", "main", 330, 19, 13, 22, 3, 0.7],
      ["leg", "Hähnchenkeule (mit Knochen)", "Chicken leg (bone-in)", "main", 160, 13, 5, 10, 4, 0.4],
      ["wing", "Chicken Wing", "Chicken wing", "main", 160, 10, 6, 11, 4, 0.4],
      ["tenders", "Tenders (3 Stk.)", "Tenders (3 pcs)", "starter", 340, 26, 20, 18],
      ["fries", "Cajun Fries (regular)", "Cajun fries (regular)", "side", 270, 4, 37, 12],
      ["rice", "Red Beans & Rice", "Red beans & rice", "side", 230, 6, 32, 9],
      ["mash", "Kartoffelpüree", "Mashed potatoes", "side", 110, 2, 16, 4],
      ["slaw", "Coleslaw", "Coleslaw", "side", 140, 1, 13, 10],
      ["biscuit", "Biscuit", "Biscuit", "side", 260, 4, 28, 15],
      ...DRINKS,
    ],
  },
  {
    id: "fiveguys", name: "Five Guys", emoji: "🍟", color: "#D31F27", type: "burger",
    items: [
      ["ham", "Hamburger", "Hamburger", "main", 700, 39, 39, 43, 1],
      ["cheese", "Cheeseburger", "Cheeseburger", "main", 840, 47, 40, 55, 1],
      ["lham", "Little Hamburger", "Little Hamburger", "main", 480, 23, 39, 26],
      ["lcheese", "Little Cheeseburger", "Little Cheeseburger", "main", 550, 27, 40, 32],
      ["bacon", "Bacon Cheeseburger", "Bacon Cheeseburger", "main", 920, 51, 40, 62, 1],
      ["hotdog", "Hot Dog", "Hot Dog", "main", 520, 18, 40, 32],
      ["veg", "Veggie Sandwich", "Veggie Sandwich", "main", 440, 10, 43, 26],
      ["friesl", "Pommes (Little)", "Fries (little)", "side", 530, 8, 72, 23],
      ["friesr", "Pommes (Regular)", "Fries (regular)", "side", 950, 14, 131, 41, 1],
      ["shake", "Milchshake", "Milkshake", "dessert", 670, 15, 90, 28],
      ...DRINKS,
    ],
  },
  {
    id: "innout", name: "In-N-Out", emoji: "🍔", color: "#E41C2B", type: "burger",
    items: [
      ["ham", "Hamburger", "Hamburger", "main", 390, 16, 39, 19],
      ["cheese", "Cheeseburger", "Cheeseburger", "main", 480, 22, 39, 27],
      ["dd", "Double-Double", "Double-Double", "main", 670, 37, 39, 41],
      ["ddps", "Double-Double Protein Style", "Double-Double Protein Style", "main", 520, 33, 11, 39],
      ["chps", "Cheeseburger Protein Style", "Cheeseburger Protein Style", "main", 330, 18, 11, 25],
      ["fries", "Pommes", "Fries", "side", 395, 7, 54, 18],
      ["shake", "Milchshake (Schoko)", "Chocolate shake", "dessert", 590, 9, 76, 28],
      ...DRINKS,
    ],
  },
  {
    id: "shake", name: "Shake Shack", emoji: "🍔", color: "#3C8D40", type: "burger",
    items: [
      ["shack", "ShackBurger", "ShackBurger", "main", 500, 26, 26, 31],
      ["double", "Double ShackBurger", "Double ShackBurger", "main", 770, 46, 27, 49, 1],
      ["smoke", "SmokeShack", "SmokeShack", "main", 590, 31, 27, 40],
      ["chick", "Chicken Shack", "Chicken Shack", "main", 590, 31, 41, 32],
      ["fries", "Pommes", "Fries", "side", 470, 6, 59, 23],
      ["shake", "Vanille-Shake", "Vanilla shake", "dessert", 690, 15, 90, 30],
      ...DRINKS,
    ],
  },
  {
    id: "arbys", name: "Arby's", emoji: "🥪", color: "#D71920", type: "sandwich",
    items: [
      ["classic", "Classic Roast Beef", "Classic Roast Beef", "main", 360, 23, 37, 14],
      ["double", "Double Roast Beef", "Double Roast Beef", "main", 450, 36, 35, 20],
      ["cheddar", "Beef 'n Cheddar", "Beef 'n Cheddar", "main", 450, 25, 42, 21],
      ["crispy", "Crispy Chicken Sandwich", "Crispy Chicken Sandwich", "main", 590, 26, 57, 30],
      ["tenders", "Chicken Tenders (3 Stk.)", "Chicken tenders (3 pcs)", "starter", 400, 25, 22, 22],
      ["curly", "Curly Fries (mittel)", "Curly fries (medium)", "side", 410, 5, 52, 21],
      ...DRINKS,
    ],
  },
  {
    id: "panda", name: "Panda Express", emoji: "🥡", color: "#D2232A", type: "asian",
    items: [
      ["orange", "Orange Chicken", "Orange chicken", "main", 490, 25, 51, 23, 2, 0.7],
      ["beijing", "Beijing Beef", "Beijing beef", "main", 480, 14, 46, 27, 2, 0.7],
      ["broccoli", "Broccoli Beef", "Broccoli beef", "main", 150, 9, 13, 7, 2, 0.7],
      ["teriyaki", "Gegrilltes Teriyaki-Hähnchen", "Grilled teriyaki chicken", "main", 275, 33, 14, 10, 2, 0.7],
      ["kungpao", "Kung Pao Chicken", "Kung Pao chicken", "main", 290, 19, 14, 19, 2, 0.7],
      ["bean", "String Bean Chicken", "String bean chicken", "main", 190, 14, 12, 9, 2, 0.7],
      ["shrimp", "Honey Walnut Shrimp", "Honey walnut shrimp", "main", 360, 13, 27, 23, 2, 0.7],
      ["rice", "Gedämpfter Reis", "Steamed white rice", "side", 380, 7, 87, 0],
      ["chowmein", "Chow Mein", "Chow mein", "side", 510, 13, 80, 20],
      ["greens", "Super Greens", "Super greens", "salad", 90, 6, 10, 3],
      ...DRINKS,
    ],
  },
  {
    id: "papajohns", name: "Papa John's", emoji: "🍕", color: "#007A33", type: "pizza",
    items: [
      ["cheese", "Cheese (1 Stück)", "Cheese (1 slice)", "main", 290, 12, 36, 10, 4, 0.4],
      ["pep", "Pepperoni (1 Stück)", "Pepperoni (1 slice)", "main", 320, 13, 35, 14, 4, 0.4],
      ["sausage", "Sausage (1 Stück)", "Sausage (1 slice)", "main", 330, 13, 35, 15, 4, 0.4],
      ["bbq", "BBQ Chicken & Bacon (1 Stück)", "BBQ chicken & bacon (1 slice)", "main", 300, 15, 37, 10, 4, 0.4],
      ["garden", "Garden Fresh (1 Stück)", "Garden fresh (1 slice)", "main", 260, 10, 36, 8, 4, 0.4],
      ["wings", "Chicken Wings (6 Stk.)", "Chicken wings (6 pcs)", "starter", 440, 33, 5, 32, 1],
      ["knots", "Garlic Knots (2 Stk.)", "Garlic knots (2 pcs)", "side", 200, 5, 32, 6],
      ...DRINKS,
    ],
  },
  {
    id: "littlecaesars", name: "Little Caesars", emoji: "🍕", color: "#F58220", type: "pizza",
    items: [
      ["cheese", "Cheese (1 Stück)", "Cheese (1 slice)", "main", 250, 11, 32, 9, 4, 0.4],
      ["pep", "Pepperoni (1 Stück)", "Pepperoni (1 slice)", "main", 280, 12, 31, 12, 4, 0.4],
      ["supreme", "Supreme (1 Stück)", "Supreme (1 slice)", "main", 300, 13, 31, 14, 4, 0.4],
      ["crazy", "Crazy Bread (2 Stk.)", "Crazy bread (2 pcs)", "side", 200, 6, 31, 6],
      ["wings", "Chicken Wings (4 Stk.)", "Chicken wings (4 pcs)", "starter", 300, 24, 5, 20],
      ...DRINKS,
    ],
  },
  {
    id: "dunkin", name: "Dunkin'", emoji: "🍩", color: "#FF671F", type: "cafe",
    items: [
      ["bagel", "Egg & Cheese Bagel", "Egg & cheese bagel", "main", 430, 19, 52, 15],
      ["wake", "Wake-Up Wrap Ei & Käse", "Wake-up wrap egg & cheese", "main", 180, 9, 13, 10, 3, 0.5],
      ["hash", "Hash Browns", "Hash browns", "side", 130, 1, 14, 8],
      ["donut", "Donut (Glasur)", "Glazed donut", "dessert", 240, 3, 31, 11],
      ["coffee", "Kaffee schwarz", "Black coffee", "drink", 5, 0, 1, 0],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "starbucks", name: "Starbucks", emoji: "☕", color: "#00704A", type: "cafe",
    items: [
      ["bites", "Egg Bites Bacon & Gruyère (2 Stk.)", "Bacon & Gruyère egg bites (2)", "main", 300, 19, 9, 20],
      ["wrap", "Egg-White Spinat-Feta-Wrap", "Spinach feta egg-white wrap", "main", 290, 20, 34, 8],
      ["turkey", "Turkey-Bacon-Cheddar-Sandwich (Eiweiss)", "Turkey bacon cheddar egg-white sandwich", "main", 230, 15, 28, 5],
      ["bowl", "Chicken-Quinoa-Protein-Bowl", "Chicken & quinoa protein bowl", "main", 420, 27, 42, 16],
      ["box", "Protein-Box mit Ei & Käse", "Eggs & cheddar protein box", "main", 460, 23, 38, 24],
      ["croissant", "Butter-Croissant", "Butter croissant", "side", 260, 5, 28, 14],
      ["latte", "Caffè Latte (Grande)", "Caffè latte (grande)", "drink", 190, 13, 19, 7],
      ["coffee", "Filterkaffee", "Brewed coffee", "drink", 5, 1, 0, 0],
    ],
  },

  /* ---------------- typical restaurants ---------------- */
  {
    id: "g_pizzeria", name: "Pizzeria / Italiener", emoji: "🍝", color: "#C8442B", type: "world", generic: true,
    items: [
      ["margh", "Pizza Margherita (ganze)", "Pizza Margherita (whole)", "main", 800, 32, 100, 30, 1],
      ["salami", "Pizza Salami (ganze)", "Pizza salami (whole)", "main", 950, 40, 100, 42, 1],
      ["quattro", "Pizza Quattro Formaggi (ganze)", "Pizza four cheese (whole)", "main", 1000, 45, 95, 48, 1],
      ["calzone", "Calzone", "Calzone", "main", 900, 38, 95, 40, 1],
      ["carbonara", "Pasta Carbonara", "Pasta carbonara", "main", 800, 32, 90, 34, 1],
      ["bolo", "Spaghetti Bolognese", "Spaghetti Bolognese", "main", 700, 30, 85, 24, 1],
      ["lasagne", "Lasagne", "Lasagne", "main", 700, 33, 55, 38, 1],
      ["caprese", "Caprese", "Caprese", "salad", 350, 20, 6, 28],
      ["mixed", "Gemischter Salat", "Mixed salad", "salad", 120, 3, 8, 8],
      ["bruschetta", "Bruschetta (3 Stk.)", "Bruschetta (3 pcs)", "starter", 300, 8, 40, 12],
      ["tiramisu", "Tiramisu", "Tiramisu", "dessert", 450, 7, 45, 26],
      ...DRINKS,
    ],
  },
  {
    id: "g_sushi", name: "Sushi / Japanisch", emoji: "🍣", color: "#2F6EBA", type: "asian", generic: true,
    items: [
      ["nigiri", "Nigiri Lachs (2 Stk.)", "Salmon nigiri (2 pcs)", "main", 120, 8, 18, 2, 4, 0.3],
      ["maki", "Maki Lachs (6 Stk.)", "Salmon maki (6 pcs)", "main", 200, 9, 36, 2, 3, 0.5],
      ["cali", "California Roll (8 Stk.)", "California roll (8 pcs)", "main", 300, 9, 46, 9, 2, 0.7],
      ["sashimi", "Sashimi Lachs (5 Stk.)", "Salmon sashimi (5 pcs)", "main", 180, 25, 0, 9, 2, 0.5],
      ["teriyaki", "Teriyaki Lachs mit Reis", "Teriyaki salmon with rice", "main", 650, 35, 70, 22, 1],
      ["chirashi", "Chirashi-Bowl", "Chirashi bowl", "main", 600, 30, 85, 12, 1],
      ["gyoza", "Gyoza (5 Stk.)", "Gyoza (5 pcs)", "starter", 250, 10, 28, 10],
      ["tempura", "Tempura Garnelen (4 Stk.)", "Shrimp tempura (4 pcs)", "starter", 280, 12, 24, 15],
      ["miso", "Miso-Suppe", "Miso soup", "starter", 40, 3, 4, 1.5],
      ["edamame", "Edamame", "Edamame", "side", 120, 11, 9, 5],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_china", name: "Chinesisch", emoji: "🥢", color: "#C9302C", type: "asian", generic: true,
    items: [
      ["friedrice", "Gebratener Reis mit Poulet", "Chicken fried rice", "main", 700, 28, 90, 24, 1],
      ["noodles", "Gebratene Nudeln", "Fried noodles", "main", 750, 25, 100, 28, 1],
      ["sweetsour", "Süss-sauer Poulet", "Sweet & sour chicken", "main", 800, 30, 95, 32, 1],
      ["duck", "Peking-Ente (1/4)", "Peking duck (1/4)", "main", 700, 45, 20, 48, 1],
      ["chopsuey", "Chop Suey", "Chop suey", "main", 500, 28, 40, 22, 1],
      ["dimsum", "Dim Sum (6 Stk.)", "Dim sum (6 pcs)", "starter", 350, 16, 40, 14],
      ["springroll", "Frühlingsrollen (2 Stk.)", "Spring rolls (2 pcs)", "starter", 300, 6, 32, 16],
      ["wonton", "Wan-Tan-Suppe", "Wonton soup", "starter", 300, 18, 30, 10],
      ["rice", "Reis", "Rice", "side", 250, 5, 55, 0.5],
      ["veg", "Gebratenes Gemüse", "Stir-fried vegetables", "side", 220, 6, 20, 13],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_india", name: "Indisch", emoji: "🍛", color: "#D4801A", type: "asian", generic: true,
    items: [
      ["butter", "Butter Chicken", "Butter chicken", "main", 550, 35, 20, 36, 1],
      ["tikka", "Chicken Tikka Masala", "Chicken tikka masala", "main", 500, 36, 22, 30, 1],
      ["tandoori", "Tandoori Chicken (2 Stücke)", "Tandoori chicken (2 pieces)", "main", 350, 45, 8, 15, 2, 0.7],
      ["rogan", "Lamm Rogan Josh", "Lamb rogan josh", "main", 600, 38, 18, 40, 1],
      ["palak", "Palak Paneer", "Palak paneer", "main", 450, 20, 15, 36, 1],
      ["dal", "Dal Tadka", "Dal tadka", "main", 300, 16, 38, 9, 1],
      ["biryani", "Biryani Chicken", "Chicken biryani", "main", 750, 35, 95, 24, 1],
      ["samosa", "Samosa (2 Stk.)", "Samosa (2 pcs)", "starter", 300, 6, 32, 17],
      ["rice", "Basmati-Reis", "Basmati rice", "side", 280, 6, 60, 1],
      ["naan", "Naan", "Naan", "side", 260, 8, 46, 5],
      ["raita", "Raita", "Raita", "extra", 80, 4, 6, 4],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_thai", name: "Thai", emoji: "🍜", color: "#2E9E6B", type: "asian", generic: true,
    items: [
      ["padthai", "Pad Thai", "Pad Thai", "main", 700, 25, 90, 26, 1],
      ["greencurry", "Grünes Curry mit Poulet & Reis", "Green curry with chicken & rice", "main", 750, 32, 80, 32, 1],
      ["friedrice", "Gebratener Reis", "Fried rice", "main", 650, 22, 90, 20, 1],
      ["satay", "Satay-Spiesse (4 Stk.)", "Satay skewers (4 pcs)", "main", 320, 28, 10, 19, 2, 0.6],
      ["tomkha", "Tom-Kha-Suppe", "Tom kha soup", "starter", 350, 18, 12, 26],
      ["tomyum", "Tom-Yum-Suppe", "Tom yum soup", "starter", 150, 14, 12, 5],
      ["somtam", "Som Tam (Papayasalat)", "Som tam (papaya salad)", "salad", 200, 6, 25, 9],
      ["mango", "Mango Sticky Rice", "Mango sticky rice", "dessert", 450, 6, 80, 12],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_ramen", name: "Ramen / Japanische Küche", emoji: "🍜", color: "#B5651D", type: "asian", generic: true,
    items: [
      ["tonkotsu", "Tonkotsu Ramen", "Tonkotsu ramen", "main", 800, 35, 85, 35, 1],
      ["shoyu", "Shoyu Ramen", "Shoyu ramen", "main", 550, 28, 70, 17, 1],
      ["katsu", "Katsu-Curry", "Katsu curry", "main", 1000, 40, 110, 45, 1],
      ["gyudon", "Gyudon (Rindfleisch-Bowl)", "Gyudon (beef bowl)", "main", 700, 25, 95, 22, 1],
      ["udon", "Udon-Suppe", "Udon soup", "main", 400, 15, 70, 6, 1],
      ["karaage", "Karaage (5 Stk.)", "Karaage (5 pcs)", "starter", 350, 22, 18, 20],
      ["onigiri", "Onigiri", "Onigiri", "side", 180, 4, 38, 1, 3, 0.4],
      ["miso", "Miso-Suppe", "Miso soup", "starter", 40, 3, 4, 1.5],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_mexico", name: "Mexikanisch (Restaurant)", emoji: "🌮", color: "#2C8A3D", type: "mexican", generic: true,
    items: [
      ["burrito", "Burrito (Poulet)", "Chicken burrito", "main", 800, 38, 85, 32, 1],
      ["tacos", "Tacos (3 Stk.)", "Tacos (3 pcs)", "main", 600, 30, 55, 28, 1],
      ["quesadilla", "Quesadilla", "Quesadilla", "main", 700, 32, 50, 40, 1],
      ["fajitas", "Fajitas (Poulet)", "Chicken fajitas", "main", 600, 45, 35, 28, 1],
      ["bowl", "Burrito Bowl", "Burrito bowl", "main", 650, 35, 75, 22, 1],
      ["nachos", "Nachos mit Käse", "Cheese nachos", "starter", 800, 22, 80, 45, 1],
      ["guac", "Guacamole & Chips", "Guacamole & chips", "starter", 450, 6, 40, 30],
      ["churros", "Churros (4 Stk.)", "Churros (4 pcs)", "dessert", 350, 4, 45, 17],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_greek", name: "Griechisch", emoji: "🥙", color: "#1F6FB5", type: "world", generic: true,
    items: [
      ["gyros", "Gyros-Teller mit Reis & Pommes", "Gyros plate with rice & fries", "main", 1100, 45, 100, 55, 1],
      ["souvlaki", "Souvlaki-Spiess (2 Stk.)", "Souvlaki skewers (2 pcs)", "main", 400, 40, 8, 22, 2, 0.6],
      ["moussaka", "Moussaka", "Moussaka", "main", 650, 28, 40, 40, 1],
      ["gemista", "Gemista", "Gemista", "main", 400, 10, 55, 16, 1],
      ["greek", "Griechischer Salat", "Greek salad", "salad", 300, 8, 14, 24],
      ["tzatziki", "Tzatziki", "Tzatziki", "extra", 120, 4, 6, 9],
      ["pita", "Pita", "Pita", "side", 250, 8, 50, 2],
      ["baklava", "Baklava (1 Stück)", "Baklava (1 piece)", "dessert", 250, 4, 28, 14],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_grill", name: "Steakhouse / Grill", emoji: "🥩", color: "#8B2E1A", type: "world", generic: true,
    items: [
      ["rump", "Rumpsteak (250 g)", "Rump steak (250 g)", "main", 600, 60, 0, 38, 1],
      ["entrecote", "Entrecôte (300 g)", "Ribeye (300 g)", "main", 750, 70, 0, 50, 1],
      ["filet", "Rindsfilet (200 g)", "Beef fillet (200 g)", "main", 400, 46, 0, 24, 1],
      ["chicken", "Pouletbrust gegrillt (300 g)", "Grilled chicken breast (300 g)", "main", 300, 50, 0, 10, 1],
      ["ribs", "Spareribs (halbe Portion)", "Spare ribs (half rack)", "main", 800, 55, 20, 55, 1],
      ["fries", "Pommes", "Fries", "side", 380, 5, 50, 18],
      ["potato", "Ofenkartoffel mit Sauerrahm", "Baked potato with sour cream", "side", 350, 7, 55, 11],
      ["salad", "Beilagensalat", "Side salad", "salad", 100, 2, 8, 6],
      ["veg", "Gegrilltes Gemüse", "Grilled vegetables", "extra", 150, 4, 14, 8],
      ["cheesecake", "Cheesecake", "Cheesecake", "dessert", 450, 7, 42, 28],
      ...[COLA_ZERO],
    ],
  },
  {
    id: "g_cafe", name: "Café / Bäckerei", emoji: "🥐", color: "#A0702A", type: "cafe", generic: true,
    items: [
      ["cheesesand", "Käse-Sandwich", "Cheese sandwich", "main", 450, 20, 45, 20],
      ["hamtoast", "Schinken-Käse-Toast", "Ham & cheese toastie", "main", 380, 18, 36, 17],
      ["chickensand", "Poulet-Sandwich", "Chicken sandwich", "main", 420, 28, 40, 16],
      ["bagel", "Lachs-Bagel", "Salmon bagel", "main", 450, 22, 50, 16],
      ["yoghurt", "Joghurt mit Müesli", "Yoghurt with muesli", "main", 300, 12, 40, 10],
      ["croissant", "Croissant", "Croissant", "side", 300, 6, 32, 16],
      ["muffin", "Muffin", "Muffin", "dessert", 420, 6, 55, 20],
      ["cake", "Rüeblitorte (1 Stück)", "Carrot cake (1 slice)", "dessert", 450, 6, 55, 24],
      ["latte", "Latte Macchiato", "Latte macchiato", "drink", 180, 10, 15, 9],
      ["cappu", "Cappuccino", "Cappuccino", "drink", 100, 6, 9, 5],
    ],
  },
  {
    id: "g_brunch", name: "Frühstück / Brunch", emoji: "🍳", color: "#E0A100", type: "cafe", generic: true,
    items: [
      ["eggs", "Rührei (3 Eier) mit Toast", "Scrambled eggs (3) with toast", "main", 450, 25, 25, 27],
      ["omelette", "Omelette Schinken & Käse", "Ham & cheese omelette", "main", 500, 32, 6, 38],
      ["benedict", "Eggs Benedict", "Eggs Benedict", "main", 650, 28, 35, 44],
      ["avotoast", "Avocado-Toast mit Ei", "Avocado toast with egg", "main", 450, 16, 35, 28],
      ["pancakes", "Pancakes (3 Stk.) mit Sirup", "Pancakes (3) with syrup", "main", 600, 10, 100, 18],
      ["frenchtoast", "French Toast", "French toast", "main", 550, 15, 70, 22],
      ["porridge", "Porridge mit Früchten", "Porridge with fruit", "main", 350, 10, 60, 7],
      ["granola", "Joghurt-Bowl mit Granola", "Yoghurt bowl with granola", "main", 400, 15, 55, 14],
      ["bacon", "Speck (3 Scheiben)", "Bacon (3 slices)", "side", 130, 9, 0, 10],
      ["oj", "Orangensaft", "Orange juice", "drink", 110, 1, 25, 0.5],
    ],
  },
];
