// Name list for the intake diary: pick a substance, the amount is typed in by the user.
// Only names, the usual form (injection / oral / gel) and a unit to start with. No doses, no cycles, no advice of any kind.
// Not on the list? The diary also takes any name typed in by hand.
// Row: [name, aliases (for the search), route, unit, group]
export const INTAKE_GROUPS = [
  { k: "inj", de: "Testosteron & Anabolika", en: "Testosterone & anabolics" },
  { k: "oral", de: "Orale", en: "Orals" },
  { k: "pct", de: "Anti-Östrogen / PCT", en: "Anti-estrogen / PCT" },
  { k: "horm", de: "Hormone", en: "Hormones" },
  { k: "gh", de: "Wachstumshormon-Peptide", en: "Growth hormone peptides" },
  { k: "pep", de: "Weitere Peptide", en: "Other peptides" },
  { k: "glp", de: "Abnehm-Spritzen (GLP-1)", en: "Weight-loss injections (GLP-1)" },
  { k: "sarm", de: "SARMs", en: "SARMs" },
  { k: "supp", de: "Begleitmittel (Leber, Blutdruck, Blutzucker)", en: "Support (liver, blood pressure, blood sugar)" },
  { k: "sleep", de: "Schlaf & Entspannung", en: "Sleep & relaxation" },
  { k: "vit", de: "Vitamine", en: "Vitamins" },
  { k: "min", de: "Mineralstoffe & Elektrolyte", en: "Minerals & electrolytes" },
  { k: "sport", de: "Sport & Aminosäuren", en: "Sports & amino acids" },
  { k: "prot", de: "Protein & Pulver", en: "Protein & powders" },
  { k: "omega", de: "Omega-3 & Fette", en: "Omega-3 & fats" },
  { k: "adapt", de: "Adaptogene & Nootropika", en: "Adaptogens & nootropics" },
  { k: "gut", de: "Verdauung & Darm", en: "Digestion & gut" },
  { k: "joint", de: "Gelenke & Regeneration", en: "Joints & recovery" },
  { k: "immune", de: "Immun, Herz & Langlebigkeit", en: "Immune, heart & longevity" },
  { k: "fat", de: "Fettstoffwechsel & Abnehmen", en: "Fat metabolism & weight loss" },
  { k: "hsup", de: "Hormon-Support (pflanzlich)", en: "Hormone support (herbal)" },
];

const R = [
  // injectable androgens and anabolics
  ["Testosteron Enantat", "testosterone enanthate test e delatestryl", "inject", "mg", "inj"],
  ["Testosteron Cypionat", "testosterone cypionate test cyp depo-testosterone", "inject", "mg", "inj"],
  ["Testosteron Propionat", "testosterone propionate test prop", "inject", "mg", "inj"],
  ["Testosteron Undecanoat", "testosterone undecanoate nebido aveed", "inject", "mg", "inj"],
  ["Testosteron-Mix (Sustanon)", "sustanon omnadren testosterone blend mix", "inject", "mg", "inj"],
  ["Testosteron Gel", "testosterone gel testogel androgel", "gel", "mg", "inj"],
  ["Nandrolon Decanoat", "nandrolone decanoate deca durabolin", "inject", "mg", "inj"],
  ["Nandrolon Phenylpropionat", "nandrolone phenylpropionate npp", "inject", "mg", "inj"],
  ["Trenbolon Acetat", "trenbolone acetate tren ace", "inject", "mg", "inj"],
  ["Trenbolon Enantat", "trenbolone enanthate tren e", "inject", "mg", "inj"],
  ["Boldenon Undecylenat", "boldenone undecylenate equipoise eq", "inject", "mg", "inj"],
  ["Drostanolon", "drostanolone masteron propionate enanthate", "inject", "mg", "inj"],
  ["Methenolon Enantat", "methenolone enanthate primobolan primo depot", "inject", "mg", "inj"],
  ["Stanozolol (Spritze)", "stanozolol winstrol depot winny", "inject", "mg", "inj"],
  // oral androgens
  ["Methandienon", "methandienone dianabol dbol d-bol", "oral", "mg", "oral"],
  ["Oxandrolon", "oxandrolone anavar var", "oral", "mg", "oral"],
  ["Stanozolol (oral)", "stanozolol winstrol winny tabletten", "oral", "mg", "oral"],
  ["Chlordehydromethyltestosteron", "turinabol tbol oral-turinabol", "oral", "mg", "oral"],
  ["Oxymetholon", "oxymetholone anadrol a-bomb", "oral", "mg", "oral"],
  ["Fluoxymesteron", "fluoxymesterone halotestin halo", "oral", "mg", "oral"],
  ["Methenolon (oral)", "methenolone acetate primobolan tabletten", "oral", "mg", "oral"],
  ["Mesterolon", "mesterolone proviron", "oral", "mg", "oral"],
  ["Methyltestosteron", "methyltestosterone", "oral", "mg", "oral"],
  // anti-estrogens, AIs, PCT and similar
  ["Tamoxifen", "nolvadex tamox", "oral", "mg", "pct"],
  ["Clomifen", "clomiphene clomid", "oral", "mg", "pct"],
  ["Enclomifen", "enclomiphene", "oral", "mg", "pct"],
  ["Anastrozol", "anastrozole arimidex adex", "oral", "mg", "pct"],
  ["Letrozol", "letrozole femara", "oral", "mg", "pct"],
  ["Exemestan", "exemestane aromasin", "oral", "mg", "pct"],
  ["Raloxifen", "raloxifene evista", "oral", "mg", "pct"],
  ["Cabergolin", "cabergoline dostinex caber", "oral", "mg", "pct"],
  ["Finasterid", "finasteride proscar propecia", "oral", "mg", "pct"],
  ["Dutasterid", "dutasteride avodart", "oral", "mg", "pct"],
  // hormones
  ["hCG (Choriongonadotropin)", "hcg human chorionic gonadotropin pregnyl ovitrelle", "inject", "IE", "horm"],
  ["HMG / FSH", "hmg fsh menopur gonal-f follitropin", "inject", "IE", "horm"],
  ["Wachstumshormon (Somatropin)", "hgh gh somatropin growth hormone genotropin norditropin", "inject", "IE", "horm"],
  ["IGF-1 LR3", "igf-1 igf1 lr3 long r3", "inject", "mcg", "horm"],
  ["L-Thyroxin (T4)", "levothyroxine l-thyroxin euthyrox t4", "oral", "mcg", "horm"],
  ["Liothyronin (T3)", "liothyronine t3 cytomel thybon", "oral", "mcg", "horm"],
  ["Oxytocin", "oxytocin nasal", "other", "IE", "horm"],
  // growth hormone secretagogues
  ["CJC-1295 (ohne DAC)", "cjc 1295 no dac mod grf 1-29 modified grf", "inject", "mcg", "gh"],
  ["CJC-1295 (mit DAC)", "cjc 1295 dac", "inject", "mg", "gh"],
  ["Ipamorelin", "ipamorelin ipa", "inject", "mcg", "gh"],
  ["GHRP-2", "ghrp2 ghrp-2 pralmorelin", "inject", "mcg", "gh"],
  ["GHRP-6", "ghrp6 ghrp-6", "inject", "mcg", "gh"],
  ["Hexarelin", "hexarelin", "inject", "mcg", "gh"],
  ["Sermorelin", "sermorelin", "inject", "mcg", "gh"],
  ["Tesamorelin", "tesamorelin egrifta", "inject", "mg", "gh"],
  ["MK-677 (Ibutamoren)", "mk677 mk-677 ibutamoren nutrobal", "oral", "mg", "gh"],
  // other peptides
  ["BPC-157", "bpc157 bpc 157 body protection compound", "inject", "mcg", "pep"],
  ["TB-500 (Thymosin Beta-4)", "tb500 tb-500 thymosin beta 4", "inject", "mg", "pep"],
  ["GHK-Cu", "ghk cu copper peptide", "inject", "mg", "pep"],
  ["Thymosin Alpha-1", "thymosin alpha 1 ta1 zadaxin", "inject", "mg", "pep"],
  ["Selank", "selank", "other", "mcg", "pep"],
  ["Semax", "semax", "other", "mcg", "pep"],
  ["PT-141 (Bremelanotid)", "pt141 pt-141 bremelanotide", "inject", "mg", "pep"],
  ["Melanotan II", "melanotan 2 mt2 mt-2", "inject", "mg", "pep"],
  ["Epitalon", "epitalon epithalon", "inject", "mg", "pep"],
  ["DSIP", "delta sleep inducing peptide dsip", "inject", "mcg", "pep"],
  ["MOTS-c", "motsc mots-c", "inject", "mg", "pep"],
  ["SS-31 (Elamipretid)", "ss31 ss-31 elamipretide", "inject", "mg", "pep"],
  ["AOD-9604", "aod9604 aod 9604", "inject", "mcg", "pep"],
  ["Kisspeptin-10", "kisspeptin kisspeptin-10", "inject", "mcg", "pep"],
  ["LL-37", "ll37 ll-37", "inject", "mcg", "pep"],
  ["KPV", "kpv", "inject", "mcg", "pep"],
  ["NAD+", "nad nad+ nicotinamide adenine dinucleotide", "inject", "mg", "pep"],
  ["Follistatin 344", "follistatin 344 fst344", "inject", "mcg", "pep"],
  // GLP-1 and similar
  ["Semaglutid", "semaglutide ozempic wegovy rybelsus", "inject", "mg", "glp"],
  ["Tirzepatid", "tirzepatide mounjaro zepbound", "inject", "mg", "glp"],
  ["Liraglutid", "liraglutide saxenda victoza", "inject", "mg", "glp"],
  ["Retatrutid", "retatrutide", "inject", "mg", "glp"],
  ["Cagrilintid", "cagrilintide", "inject", "mg", "glp"],
  // SARMs
  ["Ostarin (MK-2866)", "ostarine enobosarm mk2866 mk-2866", "oral", "mg", "sarm"],
  ["Ligandrol (LGD-4033)", "ligandrol lgd4033 lgd-4033", "oral", "mg", "sarm"],
  ["Testolon (RAD-140)", "testolone rad140 rad-140", "oral", "mg", "sarm"],
  ["Andarin (S4)", "andarine s4", "oral", "mg", "sarm"],
  ["Cardarin (GW-501516)", "cardarine gw501516 gw-501516", "oral", "mg", "sarm"],
  ["Stenabolic (SR9009)", "stenabolic sr9009", "oral", "mg", "sarm"],
  ["YK-11", "yk11 yk-11", "oral", "mg", "sarm"],
  // supplements and support (the rest is below, in groups)
  ["TUDCA", "tudca tauroursodeoxycholic", "oral", "mg", "supp"],
  ["NAC (N-Acetylcystein)", "nac n-acetylcysteine acc", "oral", "mg", "supp"],
  ["Berberin", "berberine", "oral", "mg", "supp"],
  ["Metformin", "metformin", "oral", "mg", "supp"],
  ["Telmisartan", "telmisartan micardis", "oral", "mg", "supp"],
  ["Candesartan", "candesartan atacand", "oral", "mg", "supp"],
  ["DHEA", "dhea dehydroepiandrosterone prasterone", "oral", "mg", "horm"],
  ["Pregnenolon", "pregnenolone", "oral", "mg", "horm"],
  // sleep & relaxation
  ["Melatonin", "melatonin schlafhormon circadin sleep", "oral", "mg", "sleep"],
  ["Magnesium-Glycinat (abends)", "magnesium glycinate bisglycinate sleep schlaf", "oral", "mg", "sleep"],
  ["Glycin", "glycine glycin sleep schlaf", "powder", "g", "sleep"],
  ["L-Theanin", "l-theanine theanin", "oral", "mg", "sleep"],
  ["L-Tryptophan", "tryptophan l-tryptophan", "oral", "mg", "sleep"],
  ["5-HTP", "5htp 5-htp hydroxytryptophan griffonia", "oral", "mg", "sleep"],
  ["GABA", "gaba gamma-aminobutyric acid aminobuttersäure", "oral", "mg", "sleep"],
  ["Baldrian", "valerian valeriana baldrianwurzel", "oral", "mg", "sleep"],
  ["Passionsblume", "passionflower passiflora passionsblume", "oral", "mg", "sleep"],
  ["Hopfen-Extrakt", "hops hopfen humulus", "oral", "mg", "sleep"],
  ["Zitronenmelisse", "lemon balm melissa zitronenmelisse", "oral", "mg", "sleep"],
  ["Lavendelöl (Silexan)", "lavender silexan lavendel lasea", "oral", "mg", "sleep"],
  ["Apigenin", "apigenin chamomile kamille", "oral", "mg", "sleep"],
  ["Phosphatidylserin", "phosphatidylserine ps cortisol", "oral", "mg", "sleep"],
  ["Ashwagandha (KSM-66)", "ashwagandha ksm66 ksm-66 withania somnifera schlafbeere", "oral", "mg", "sleep"],
  ["Inositol (Myo-Inositol)", "inositol myo-inositol pcos", "powder", "g", "sleep"],
  // vitamins
  ["Vitamin D3", "vitamin d d3 cholecalciferol sonnenvitamin", "oral", "IE", "vit"],
  ["Vitamin D3 + K2", "vitamin d3 k2 d3k2 mk7", "oral", "IE", "vit"],
  ["Vitamin K2 (MK-7)", "vitamin k2 mk7 mk-7 menaquinone", "oral", "mcg", "vit"],
  ["Vitamin C", "vitamin c ascorbic acid ascorbinsäure", "oral", "mg", "vit"],
  ["Vitamin B12 (Methylcobalamin)", "vitamin b12 methylcobalamin cobalamin cyanocobalamin", "oral", "mcg", "vit"],
  ["Vitamin B-Komplex", "b complex b-komplex vitamin b", "oral", "Stk", "vit"],
  ["Vitamin B6 (P-5-P)", "vitamin b6 pyridoxine p5p pyridoxal", "oral", "mg", "vit"],
  ["Vitamin B1 (Thiamin / Benfotiamin)", "vitamin b1 thiamine benfotiamine", "oral", "mg", "vit"],
  ["Vitamin B2 (Riboflavin)", "vitamin b2 riboflavin", "oral", "mg", "vit"],
  ["Vitamin B3 (Niacin)", "vitamin b3 niacin nicotinic acid nicotinamid", "oral", "mg", "vit"],
  ["Vitamin B5 (Pantothensäure)", "vitamin b5 pantothenic acid pantothensäure", "oral", "mg", "vit"],
  ["Folat (Methylfolat)", "folate methylfolate folsäure folic acid 5-mthf b9", "oral", "mcg", "vit"],
  ["Biotin", "biotin vitamin b7 vitamin h haare nägel", "oral", "mcg", "vit"],
  ["Vitamin A (Retinol)", "vitamin a retinol retinyl beta-carotin", "oral", "IE", "vit"],
  ["Vitamin E (Tocopherol)", "vitamin e tocopherol tocotrienol", "oral", "IE", "vit"],
  ["Multivitamin", "multivitamin multivitamine multi mineral", "oral", "Stk", "vit"],
  ["Cholin", "choline cholin lecithin", "oral", "mg", "vit"],
  // minerals & electrolytes
  ["Magnesium", "magnesium", "oral", "mg", "min"],
  ["Magnesium-Citrat", "magnesium citrate citrat", "oral", "mg", "min"],
  ["Magnesium-Malat", "magnesium malate malat", "oral", "mg", "min"],
  ["Magnesium-Threonat", "magnesium threonate l-threonat magtein", "oral", "mg", "min"],
  ["Zink", "zinc zink", "oral", "mg", "min"],
  ["Zink-Bisglycinat", "zinc bisglycinate zink glycinat", "oral", "mg", "min"],
  ["Zink-Picolinat", "zinc picolinate zink picolinat", "oral", "mg", "min"],
  ["Eisen", "iron eisen ferrum bisglycinat ferrous", "oral", "mg", "min"],
  ["Kalzium", "calcium kalzium", "oral", "mg", "min"],
  ["Kalium", "potassium kalium", "oral", "mg", "min"],
  ["Natrium / Salz (Elektrolyte)", "sodium salt natrium salz elektrolyte electrolytes", "powder", "mg", "min"],
  ["Elektrolyt-Mix", "electrolyte mix elektrolyte lmnt drip drop", "powder", "g", "min"],
  ["Jod", "iodine jod jodid kelp", "oral", "mcg", "min"],
  ["Selen", "selenium selen selenomethionin", "oral", "mcg", "min"],
  ["Kupfer", "copper kupfer", "oral", "mg", "min"],
  ["Bor", "boron bor borax", "oral", "mg", "min"],
  ["Chrom (Picolinat)", "chromium chrom picolinate", "oral", "mcg", "min"],
  ["Lithium-Orotat", "lithium orotate orotat", "oral", "mg", "min"],
  ["Silizium", "silicon silica silizium kieselerde orthokieselsäure", "oral", "mg", "min"],
  // sport & amino acids
  ["Kreatin Monohydrat", "creatine monohydrate creapure kreatin", "powder", "g", "sport"],
  ["Kreatin HCl", "creatine hcl hydrochloride", "oral", "g", "sport"],
  ["Citrullin (Malat)", "citrulline malate l-citrulline citrullin", "powder", "g", "sport"],
  ["Arginin", "arginine l-arginine arginin akg", "oral", "g", "sport"],
  ["Beta-Alanin", "beta alanine beta-alanine carnosyn", "powder", "g", "sport"],
  ["BCAA", "bcaa branched chain amino acids leucin isoleucin valin", "powder", "g", "sport"],
  ["EAA (essentielle Aminosäuren)", "eaa essential amino acids aminosäuren", "powder", "g", "sport"],
  ["Leucin", "leucine l-leucine leucin", "powder", "g", "sport"],
  ["Glutamin", "glutamine l-glutamine glutamin", "powder", "g", "sport"],
  ["L-Carnitin", "carnitine l-carnitine carnitin tartrat", "oral", "mg", "sport"],
  ["Acetyl-L-Carnitin (ALCAR)", "acetyl l carnitine alcar acetylcarnitin", "oral", "mg", "sport"],
  ["HMB", "hmb beta-hydroxy beta-methylbutyrat", "oral", "g", "sport"],
  ["Taurin", "taurine taurin", "oral", "g", "sport"],
  ["Betain (TMG)", "betaine tmg trimethylglycine betain", "oral", "g", "sport"],
  ["Carnosin", "carnosine carnosin", "oral", "mg", "sport"],
  ["Tyrosin", "tyrosine l-tyrosine tyrosin", "oral", "mg", "sport"],
  ["Koffein", "caffeine koffein kaffee coffee", "oral", "mg", "sport"],
  ["Pre-Workout (Booster)", "pre workout preworkout booster pump", "powder", "g", "sport"],
  ["Rote-Bete-Extrakt (Nitrat)", "beetroot nitrate rote bete rübe", "powder", "g", "sport"],
  ["Cordyceps", "cordyceps militaris sinensis", "oral", "mg", "sport"],
  ["Energy Gel / Kohlenhydrat-Pulver", "energy gel carbs maltodextrin dextrose cluster dextrin", "powder", "g", "sport"],
  // protein & powders
  ["Whey Protein (Konzentrat)", "whey protein wpc molkenprotein konzentrat", "powder", "g", "prot"],
  ["Whey Isolat", "whey isolate wpi molkenprotein isolat", "powder", "g", "prot"],
  ["Whey Hydrolysat", "whey hydrolysate hydrolysat", "powder", "g", "prot"],
  ["Casein", "casein micellar kasein caseinat", "powder", "g", "prot"],
  ["Pflanzenprotein (Erbse / Reis / Soja)", "plant protein vegan pea rice soy erbsenprotein sojaprotein", "powder", "g", "prot"],
  ["Mehrkomponenten-Protein", "protein blend multi component", "powder", "g", "prot"],
  ["Eiprotein", "egg protein eiprotein eiklar", "powder", "g", "prot"],
  ["Kollagen-Peptide", "collagen peptides kollagen hydrolysat verisol", "powder", "g", "prot"],
  ["Mass Gainer", "mass gainer weight gainer", "powder", "g", "prot"],
  ["Proteinriegel", "protein bar proteinriegel", "oral", "Stk", "prot"],
  // omega-3 & fats
  ["Omega-3 (Fischöl)", "omega 3 fish oil fischöl epa dha", "oral", "mg", "omega"],
  ["Krillöl", "krill oil krillöl", "oral", "mg", "omega"],
  ["Algenöl (vegan Omega-3)", "algae oil algal omega 3 algenöl vegan", "oral", "mg", "omega"],
  ["MCT-Öl", "mct oil mct-öl caprylic c8 c10", "other", "ml", "omega"],
  ["Leinöl", "flaxseed linseed oil leinöl", "other", "ml", "omega"],
  ["CLA", "cla conjugated linoleic acid linolsäure", "oral", "mg", "omega"],
  ["Lecithin", "lecithin soja sonnenblumen", "oral", "mg", "omega"],
  ["Olivenöl (nativ extra)", "olive oil olivenöl", "other", "ml", "omega"],
  // adaptogens & nootropics
  ["Ashwagandha", "ashwagandha withania", "oral", "mg", "adapt"],
  ["Rhodiola rosea", "rhodiola rosea rosenwurz", "oral", "mg", "adapt"],
  ["Ginseng (Panax)", "ginseng panax korean koreanischer", "oral", "mg", "adapt"],
  ["Maca", "maca peruvian ginseng", "oral", "mg", "adapt"],
  ["Lion's Mane (Igelstachelbart)", "lions mane lion's mane hericium igelstachelbart", "oral", "mg", "adapt"],
  ["Reishi", "reishi ganoderma lucidum", "oral", "mg", "adapt"],
  ["Bacopa Monnieri", "bacopa monnieri brahmi", "oral", "mg", "adapt"],
  ["Ginkgo biloba", "ginkgo biloba", "oral", "mg", "adapt"],
  ["Alpha-GPC", "alpha gpc alpha-gpc glycerylphosphorylcholin", "oral", "mg", "adapt"],
  ["Citicolin (CDP-Cholin)", "citicoline cdp choline cognizin citicolin", "oral", "mg", "adapt"],
  ["Schisandra", "schisandra chinesische beerenfrucht", "oral", "mg", "adapt"],
  ["Shilajit", "shilajit fulvic fulvinsäure", "oral", "mg", "adapt"],
  ["Heilpilz-Mix", "mushroom blend heilpilze pilz mix chaga turkey tail", "oral", "mg", "adapt"],
  ["Nootropika-Mischung", "nootropic stack nootropika focus", "oral", "Stk", "adapt"],
  // digestion & gut
  ["Probiotika", "probiotic probiotika lactobacillus bifidobacterium cfu", "oral", "Stk", "gut"],
  ["Präbiotika (Inulin)", "prebiotic inulin präbiotika fos gos", "powder", "g", "gut"],
  ["Verdauungsenzyme", "digestive enzymes verdauungsenzyme", "oral", "Stk", "gut"],
  ["Flohsamenschalen (Psyllium)", "psyllium husk flohsamen ballaststoffe", "powder", "g", "gut"],
  ["Ballaststoffe", "fiber fibre ballaststoffe", "powder", "g", "gut"],
  ["Betain HCl", "betaine hcl magensäure", "oral", "mg", "gut"],
  ["Ingwer", "ginger ingwer", "oral", "mg", "gut"],
  ["Pfefferminzöl", "peppermint oil pfefferminzöl", "oral", "mg", "gut"],
  ["Aktivkohle", "charcoal activated aktivkohle kohle", "oral", "mg", "gut"],
  ["Colostrum", "colostrum biestmilch", "powder", "g", "gut"],
  ["Butyrat", "butyrate butyrat", "oral", "mg", "gut"],
  ["Saccharomyces boulardii", "saccharomyces boulardii hefe probiotikum perenterol", "oral", "mg", "gut"],
  ["Apfelessig", "apple cider vinegar apfelessig", "other", "ml", "gut"],
  // joints & recovery
  ["Glucosamin", "glucosamine glucosamin sulfat", "oral", "mg", "joint"],
  ["Chondroitin", "chondroitin sulfat", "oral", "mg", "joint"],
  ["MSM", "msm methylsulfonylmethane", "oral", "mg", "joint"],
  ["Kollagen Typ II (UC-II)", "collagen type 2 uc-ii kollagen typ 2", "oral", "mg", "joint"],
  ["Hyaluronsäure", "hyaluronic acid hyaluron", "oral", "mg", "joint"],
  ["Curcumin / Kurkuma", "curcumin turmeric kurkuma piperin", "oral", "mg", "joint"],
  ["Boswellia (Weihrauch)", "boswellia frankincense weihrauch", "oral", "mg", "joint"],
  ["Bromelain", "bromelain ananas", "oral", "mg", "joint"],
  ["Tart-Cherry (Sauerkirsche)", "tart cherry sauerkirsche montmorency", "oral", "mg", "joint"],
  ["Astaxanthin", "astaxanthin", "oral", "mg", "joint"],
  ["Eierschalenmembran", "eggshell membrane eierschalenmembran natupure", "oral", "mg", "joint"],
  ["Vitamin C + Kollagen (Sehnen)", "vitamin c collagen tendon sehnen gelatine", "powder", "g", "joint"],
  // immune, heart & longevity
  ["Quercetin", "quercetin", "oral", "mg", "immune"],
  ["Holunder (Sambucus)", "elderberry sambucus holunder", "oral", "mg", "immune"],
  ["Echinacea", "echinacea sonnenhut", "oral", "mg", "immune"],
  ["Propolis", "propolis", "oral", "mg", "immune"],
  ["Beta-Glucan", "beta glucan betaglucan", "oral", "mg", "immune"],
  ["Knoblauch-Extrakt", "garlic extract knoblauch allicin", "oral", "mg", "immune"],
  ["Coenzym Q10 (Ubiquinol)", "coq10 coenzyme q10 ubiquinol ubiquinon", "oral", "mg", "immune"],
  ["PQQ", "pqq pyrroloquinoline quinone", "oral", "mg", "immune"],
  ["Nattokinase", "nattokinase natto", "oral", "mg", "immune"],
  ["Resveratrol", "resveratrol trans-resveratrol", "oral", "mg", "immune"],
  ["NMN", "nmn nicotinamide mononucleotide", "oral", "mg", "immune"],
  ["Nicotinamid-Ribosid (NR)", "nr nicotinamide riboside niagen tru niagen", "oral", "mg", "immune"],
  ["Spermidin", "spermidine spermidin weizenkeim", "oral", "mg", "immune"],
  ["Alpha-Liponsäure", "alpha lipoic acid ala liponsäure r-ala", "oral", "mg", "immune"],
  ["Lycopin", "lycopene lycopin", "oral", "mg", "immune"],
  ["OPC (Traubenkernextrakt)", "opc grape seed extract traubenkern", "oral", "mg", "immune"],
  ["Sulforaphan (Brokkoli-Extrakt)", "sulforaphane sulforaphan broccoli brokkoli", "oral", "mg", "immune"],
  ["Glutathion", "glutathione glutathion liposomal", "oral", "mg", "immune"],
  ["Fisetin", "fisetin trans-fisetin", "oral", "mg", "immune"],
  // fat metabolism & weight loss
  ["Grüntee-Extrakt (EGCG)", "green tea extract egcg grüntee matcha", "oral", "mg", "fat"],
  ["Glucomannan", "glucomannan konjac", "oral", "g", "fat"],
  ["Ceylon-Zimt", "cinnamon ceylon zimt", "oral", "mg", "fat"],
  ["Capsaicin (Chili-Extrakt)", "capsaicin chili cayenne capsimax", "oral", "mg", "fat"],
  ["Garcinia cambogia", "garcinia cambogia hca", "oral", "mg", "fat"],
  ["Synephrin (Bitterorange)", "synephrine bitter orange bitterorange", "oral", "mg", "fat"],
  ["Yohimbin", "yohimbine yohimbin yohimbe", "oral", "mg", "fat"],
  // herbal hormone support
  ["Tongkat Ali", "tongkat ali eurycoma longifolia", "oral", "mg", "hsup"],
  ["Fadogia Agrestis", "fadogia agrestis", "oral", "mg", "hsup"],
  ["Tribulus terrestris", "tribulus terrestris burzeldorn", "oral", "mg", "hsup"],
  ["Bockshornklee (Fenugreek)", "fenugreek bockshornklee testofen", "oral", "mg", "hsup"],
  ["D-Asparaginsäure (DAA)", "d-aspartic acid daa asparaginsäure", "powder", "g", "hsup"],
  ["DIM (Diindolylmethan)", "dim diindolylmethane", "oral", "mg", "hsup"],
  ["Saw Palmetto (Sägepalme)", "saw palmetto sägepalme", "oral", "mg", "hsup"],
  ["Brennnesselwurzel", "stinging nettle root brennnessel urtica", "oral", "mg", "hsup"],
  ["Mönchspfeffer (Vitex)", "vitex agnus castus chasteberry mönchspfeffer", "oral", "mg", "hsup"],
  ["Kürbiskern-Extrakt", "pumpkin seed kürbiskern", "oral", "mg", "hsup"],
  ["Chrysin", "chrysin passionflower", "oral", "mg", "hsup"],
  ["Mucuna pruriens (L-Dopa)", "mucuna pruriens velvet bean l-dopa", "oral", "mg", "hsup"],
];

export const INTAKE_CATALOG = R.map(([n, a, r, u, g]) => ({ n, a: n.toLowerCase() + " " + a, r, u, g }));

export function searchIntake(query, group) {
  const toks = String(query || "").toLowerCase().split(/\s+/).filter(Boolean);
  return INTAKE_CATALOG.filter((x) => (group === "all" || x.g === group) && toks.every((tok) => x.a.includes(tok)));
}
